export const GET_CINEMAS = "GET_CINEMAS";
export const GET_CINEMA = "GET_CINEMA";
export const CREATE_CINEMA = "CREATE_CINEMA";
export const UPDATE_CINEMA = "UPDATE_CINEMA";
export const DELETE_CINEMA = "DELETE_CINEMA";