export const GET_SEANCES_BY_CINEMA = "GET_SEANCES_BY_CINEMA";
export const GET_SEANCES_BY_MOVIE = "GET_SEANCES_BY_MOVIE";
export const GET_SEANCE = "GET_SEANCE";
export const GET_SEANCES = "GET_SEANCES";
export const CREATE_SEANCE = "CREATE_SEANCE";
export const UPDATE_SEANCE = "UPDATE_SEANCE";
export const DELETE_SEANCE = "DELETE_SEANCE";