export const GET_SEATS_BY_HALL = "GET_SEATS_BY_HALL";
export const SAVE_SEATS_BY_HALL = "SAVE_SEATS_BY_HALL";
export const UPDATE_SEAT_BY_HALL = "UPDATE_SEAT_BY_HALL";
export const UPDATE_SEATS_SIZE = "UPDATE_SEATS_SIZE";
export const UPDATE_SEATS_PRICE = "UPDATE_SEATS_PRICE";